### PR TITLE
posts license plate and resets parking spot after submit

### PR DESCRIPTION
**Pull request by jonathanSeang**
Clearing values now takes place after sending POST to backend. Also, parking spot gets reset to null after submitting.

### CODE REVIEW

**Comment by martinn8145** [comment]
lgtm, but it was already working for me before this commit, so wait on others to comment before merge.

**Comment by johnpaultran** [comment]
looks good

**Comment by asacaasi** [comment]
changes look good

**Comment by cmtnguyen** [comment]
all good!

**Pull request merged**
