### PR TITLE
already reserved parking spot buttons are now disabled

### PR DESCRIPTION
**Pull request by jonathanSeang**

### CODE REVIEW

**Comment by johnpaultran** [comment]
lgtm

**Comment by martinn8145** [comment]
Doesn't work on my end. I tried reserving parking spot G for 6pm. That spot gets disabled, but when I refresh, or try reserving again after viewing the reservation, I'm still able to reserve the duplicate.

**Comment by jonathanSeang** [comment]
Ah, it looks like when reservation gets sent to backend, Date stores minutes. Then when trying to GET with date, minutes are not specified. I'll send a pull request to both repos to truncate minutes from being added and read.

**Comment by martinn8145** [comment]
Working now! Good stuff.

**Comment by cmtnguyen** [comment]
everything works!

**Pull request merged**
